[install]
auto = "fallback"
peer = false
exact = false

[install.cache]
dir = "~/.bun/install/cache"
disable = false
disableManifest = false

[test]
preload = ["./tests/setup.ts"]
# Disable parallel execution to prevent global state interference
concurrency = 1

[run]
bun = true